# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        arguments:  ["@jms_serializer"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
