<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findTaskPostman($id){
        return $this->getEntityManager()->createQuery("SELECT t FROM AppBundle:Task t WHERE t.postman = :id")
                ->setParameter("id", $id)
                ->getResult();
    }
}
