app_parcel_order:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\ParcelOrderController'
    name_prefix: api_1_parcelorder_

app_user:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\UserController'
    name_prefix: api_1_user_
    
app_postman:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\PostmanController'
    name_prefix: api_1_postman_   

app_task:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\TaskController'
    name_prefix: api_1_task_

app_receiver:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\ReceiverController'
    name_prefix: api_1_user_
